# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import assignment1_pb2 as assignment1__pb2


class FrequencyCalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Calculate = channel.unary_unary(
                '/assignment1.FrequencyCalculator/Calculate',
                request_serializer=assignment1__pb2.Message.SerializeToString,
                response_deserializer=assignment1__pb2.Map.FromString,
                )
        self.Combine = channel.stream_unary(
                '/assignment1.FrequencyCalculator/Combine',
                request_serializer=assignment1__pb2.MessageResponse.SerializeToString,
                response_deserializer=assignment1__pb2.Map.FromString,
                )


class FrequencyCalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Calculate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Combine(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrequencyCalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Calculate': grpc.unary_unary_rpc_method_handler(
                    servicer.Calculate,
                    request_deserializer=assignment1__pb2.Message.FromString,
                    response_serializer=assignment1__pb2.Map.SerializeToString,
            ),
            'Combine': grpc.stream_unary_rpc_method_handler(
                    servicer.Combine,
                    request_deserializer=assignment1__pb2.MessageResponse.FromString,
                    response_serializer=assignment1__pb2.Map.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'assignment1.FrequencyCalculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FrequencyCalculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Calculate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/assignment1.FrequencyCalculator/Calculate',
            assignment1__pb2.Message.SerializeToString,
            assignment1__pb2.Map.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Combine(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/assignment1.FrequencyCalculator/Combine',
            assignment1__pb2.MessageResponse.SerializeToString,
            assignment1__pb2.Map.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
